// Generated by LiveScript 1.2.0
(function(){
  module.exports.parse = function(csvString, cb){
    var lines;
    lines = csvString.split("\n");
    lines.shift();
    return lines.filter(function(it){
      return it.length;
    }).map(function(line){
      var ref$, id, _, name, abbr;
      ref$ = line.split(";"), id = ref$[0], _ = ref$[1], name = ref$[2], _ = ref$[3], _ = ref$[4], abbr = ref$[5];
      id = +id;
      return {
        id: id,
        name: name,
        abbr: abbr
      };
    });
  };
}).call(this);
