// Generated by LiveScript 1.2.0
(function(){
  var getPartiesFromKrajmesta, getPartiesFromMain;
  module.exports.parse = function(xml){
    var root;
    root = xml["VYSLEDKY_KRAJMESTA"] || xml["VYSLEDKY"];
    return root["KRAJ"].map(function(kraj){
      var name, id, that, parties, ucast, votes, attendance_max, attendance_actual, processed_target, processed_actual;
      name = kraj.$.NAZ_KRAJ;
      id = +kraj.$.CIS_KRAJ;
      if (that = kraj.CELKEM) {
        parties = getPartiesFromKrajmesta(that);
        ucast = kraj.CELKEM[0].UCAST[0].$;
      } else {
        parties = getPartiesFromMain(kraj);
        ucast = kraj.UCAST[0].$;
      }
      votes = +ucast.PLATNE_HLASY;
      attendance_max = +ucast.ZAPSANI_VOLICI;
      attendance_actual = +ucast.VYDANE_OBALKY;
      processed_target = +ucast.OKRSKY_CELKEM;
      processed_actual = +ucast.OKRSKY_ZPRAC;
      return {
        id: id,
        name: name,
        votes: votes,
        attendance_max: attendance_max,
        attendance_actual: attendance_actual,
        processed_target: processed_target,
        processed_actual: processed_actual,
        parties: parties
      };
    });
  };
  getPartiesFromKrajmesta = function(celkem){
    return celkem[0].HLASY_STRANA.map(function(strana){
      var id, votes;
      id = +strana.$.KSTRANA;
      votes = +strana.$.HLASY;
      return {
        id: id,
        votes: votes
      };
    });
  };
  getPartiesFromMain = function(kraj){
    return kraj.STRANA.map(function(strana){
      var id, votes;
      id = +strana.$.KSTRANA;
      votes = +strana.HODNOTY_STRANA[0].$.HLASY;
      return {
        id: id,
        votes: votes
      };
    });
  };
}).call(this);
