// Generated by LiveScript 1.2.0
(function(){
  var xml2js;
  xml2js = require('xml2js');
  module.exports.parse_county_list = function(xmlString, cb){
    var this$ = this;
    return xml2js.parseString(xmlString, function(err, xml){
      if (err) {
        cb(err);
      }
      return cb(null, xml["VYSLEDKY_KRAJMESTA"]["KRAJ"].map(function(kraj){
        var name, id, votes, parties;
        name = kraj.$.NAZ_KRAJ;
        id = +kraj.$.CIS_KRAJ;
        votes = +kraj.CELKEM[0].UCAST[0].$.PLATNE_HLASY;
        parties = kraj.CELKEM[0].HLASY_STRANA.map(function(strana){
          var id, votes;
          id = +strana.$.KSTRANA;
          votes = +strana.$.HLASY;
          return {
            id: id,
            votes: votes
          };
        });
        return {
          id: id,
          name: name,
          votes: votes,
          parties: parties
        };
      }));
    });
  };
}).call(this);
