// Generated by LiveScript 1.2.0
(function(){
  var getPartiesFromKrajmesta, getPartiesFromMain;
  module.exports.parse = function(xml){
    var root;
    root = xml["VYSLEDKY_KRAJMESTA"] || xml["VYSLEDKY"];
    return root["KRAJ"].map(function(kraj){
      var name, id, that, parties, votes;
      name = kraj.$.NAZ_KRAJ;
      id = +kraj.$.CIS_KRAJ;
      if (that = kraj.CELKEM) {
        parties = getPartiesFromKrajmesta(that);
        votes = +kraj.CELKEM[0].UCAST[0].$.PLATNE_HLASY;
      } else {
        parties = getPartiesFromMain(kraj);
        votes = +kraj.UCAST[0].$.PLATNE_HLASY;
      }
      return {
        id: id,
        name: name,
        votes: votes,
        parties: parties
      };
    });
  };
  getPartiesFromKrajmesta = function(celkem){
    return celkem[0].HLASY_STRANA.map(function(strana){
      var id, votes;
      id = +strana.$.KSTRANA;
      votes = +strana.$.HLASY;
      return {
        id: id,
        votes: votes
      };
    });
  };
  getPartiesFromMain = function(kraj){
    return kraj.STRANA.map(function(strana){
      var id, votes;
      id = +strana.$.KSTRANA;
      votes = +strana.HODNOTY_STRANA[0].$.HLASY;
      return {
        id: id,
        votes: votes
      };
    });
  };
}).call(this);
