// Generated by LiveScript 1.2.0
(function(){
  module.exports.parse = function(xml){
    return xml["VYSLEDKY_KRAJMESTA"]["KRAJ"].map(function(kraj){
      var name, id, votes, parties;
      name = kraj.$.NAZ_KRAJ;
      id = +kraj.$.CIS_KRAJ;
      votes = +kraj.CELKEM[0].UCAST[0].$.PLATNE_HLASY;
      parties = kraj.CELKEM[0].HLASY_STRANA.map(function(strana){
        var id, votes;
        id = +strana.$.KSTRANA;
        votes = +strana.$.HLASY;
        return {
          id: id,
          votes: votes
        };
      });
      return {
        id: id,
        name: name,
        votes: votes,
        parties: parties
      };
    });
  };
}).call(this);
