// Generated by LiveScript 1.2.0
(function(){
  module.exports.compute = function(candidates, partyVotes, options){
    var voteAccessor, threshold, preferredCandidates, deferredCandidates, sortedOutput, that;
    voteAccessor = options.voteAccessor, threshold = options.threshold;
    preferredCandidates = [];
    deferredCandidates = [];
    candidates.forEach(function(candidate){
      var candidateVotes, percent, list;
      candidateVotes = options.voteAccessor(candidate);
      percent = candidateVotes / partyVotes;
      list = percent >= options.threshold ? preferredCandidates : deferredCandidates;
      return list.push(candidate);
    });
    preferredCandidates.sort(function(a, b){
      var votesA, votesB;
      votesA = options.voteAccessor(a);
      votesB = options.voteAccessor(b);
      return votesB - votesA;
    });
    sortedOutput = preferredCandidates.concat(deferredCandidates);
    if (that = options.resultProperty) {
      sortedOutput.forEach(function(candidate, index){
        return candidate[that] = index;
      });
    }
    return sortedOutput;
  };
}).call(this);
